### ISSUE TITLE
Add velocity support

### ISSUE THREAD

**Issue by MagicTeaMC** [KyotoResources/BetterSecurity#5]
Can you add velocity support?

**Comment by zS0bye** [comment]
Sorry for the delay, I read now. Velocity support will come out in the next version. You can find the dev version here: https://dev.kyotoresources.space/job/BetterSecurity/

But currently it is still under development, you can find all the updates in jenkins "changes" tab. And to be more updated you can also join our discord: https://ds.kyotoresources.space.

If you need anything else, or have suggestions to implement in the next version, don't hesitate to contact me ;)

**Comment by MagicTeaMC** [comment]
thank you!
